config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  root to:"posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class User < ApplicationRecord
  has_many :posts
end
class Post < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord 
    validates :title, :content, :presence =>true
    validates :title, :length => { :minimum =>2}
    validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @posts = Post.all
    end

    def show
      @post = Post.find(params[:id])
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to posts_path, :notice => "your post was saved"
      else
        render "new"
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path, :notice => "post has been updated"
      else
        render "edit" 
      end

    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path, :notice => "your post has been deleted"
    end

    private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/Blog/index.html.erb
# start
<%= link_to 'New Shark', new_shark_path, :class => "btn btn-primary btn-sm" %> <%= link_to 'Home', index_path, :class => "btn btn-primary btn-sm" %>

app/views/blog/edit.html.erb
# start
<%= link_to 'Show', @post, :class => "btn btn-primary btn-sm" %> <%= link_to 'Back', posts_path, :class => "btn btn-primary btn-sm" %>

app/views/blog/new.html.erb
# start
<%= link_to 'Back', sharks_path, :class => "btn btn-primary btn-sm" %>

app/views/blog/show.html.erb
# start
<%= link_to 'Edit', edit_blog_path(@post), :class => "btn btn-primary btn-sm" %> <%= link_to 'Back', posts_path, :class => "btn btn-primary btn-sm" %> 

app/views/home/index.html.erb
<div class="jumbotron">
<div class="container">
    <h1>Want to Learn About Sharks?</h1>
    <p>Are you ready to learn about sharks?</p>
    <br>
    <p>
        <%= button_to 'Get Shark Info', sharks_path, :method => :get,  :class => "btn btn-primary btn-lg"%>
    </p>
</div>
</div>
<div class="container">
<div class="row">
    <div class="col-lg-6">
        <h3>Not all sharks are alike</h3>
        <p>Though some are dangerous, sharks generally do not attack humans. 
          Out of the 500 species known to researchers, only 30 have been known to attack humans.
        </p>
    </div>
    <div class="col-lg-6">
        <h3>Sharks are ancient</h3>
        <p>There is evidence to suggest that sharks lived up to 400 million years ago.</p>
    </div>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
        </button> <%= link_to "Everything Blog", posts_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <li class='nav-item'><%= link_to 'Home', posts_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Blog', posts_path, class: 'nav-link' %></li>

                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>

  <nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">Navbar</a>
  <form class="form-inline">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  </nav>

    <%= render 'layouts/navigation' %>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% flash.each do |key, value|%>
    <p><%= value %></p>
  <%end%>

  <main role="main">
  <%= content_for?(:content) ? yield(:content) : yield %>
  </main>
  </body>
</html>

app/views/layouts/blog.html.erb
<% content_for :content do %>
    <div class="jumbotron text-center">
        <h1>Blog Info</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <%= yield %>
                </p>
            </div>
            <div class="col-lg-6">
                <p>

                    <div class="caption">You can always count on some blogs to be friendly and welcoming!</div>
                    <img src="https://assets.digitalocean.com/articles/docker_node_image/sammy.png" alt="Sammy the Shark">
                </p>

            </div>
        </div>
    </div>
<% end %>
    <%= render template: "layouts/application" %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f|%>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title%>
    </p>
    <p>
        <%= f.label :content %><br />
        <%= f.text_area :content%>
    </p>
    <p>
    <%= f.submit "Update Post" %>
    </p>
<% end %>

app/views/posts/index.html.erb
# start
<h1 class btn btn-primary btn-sm >My Blog</h1>

<%= link_to 'sign out', destroy_user_session_path, method: :delete %>

<p><%= link_to "Add a new post", new_post_path %></p>

<% @posts.each do |post| %>
    <h2><%= link_to post.title, post %></h2>
    <p><%= post.content%></p>
    <p>
        <%= link_to "Edit", edit_post_path(post) %> ||
        <%= link_to "Delete", post, :confirm => "are You sure?", :method => :delete %>
    </p>
    <hr/>
<% end %>

app/views/posts/new.html.erb
<h1> Add a New Post</h1>
<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title%>
    </p>
    <p>
        <%= f.label :content %><br />
        <%= f.text_area :content%>
    </p>
    <p>
    <%= f.submit "Add a New Post" %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<small><h1>created at</h1><%= @post.created_at %></small>
<small><h1>updated at</h1><%= @post.updated_at %></small>
<small><h1>Post Id</h1></small><%= @post.id %>